# Generated by Django 5.1.1 on 2025-04-25 14:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        max_length=500,
                    ),
                ),
                (
                    "date_posted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "commenter",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
                (
                    "dislikes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="comment_dislikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="comment_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replies",
                    models.ManyToManyField(
                        blank=True, related_name="comment_replies", to="videos.comment"
                    ),
                ),
                (
                    "replying_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_to",
                        to="videos.comment",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_posted"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "notification_message",
                    models.CharField(
                        default="new video",
                        max_length=50,
                        null=True,
                        validators=[],
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=75, validators=[]
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        validators=[],
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        help_text="(must be an mp4 or mov between 1kb and 5gb and be under 2 hours)",
                        upload_to="media/uploads/video_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "mov"]
                            )
                        ],
                    ),
                ),
                (
                    "thumbnail",
                    models.FileField(
                        blank=True,
                        help_text="(must be a png or jpg between 1kb and 10mb)",
                        upload_to="media/uploads/thumbnails/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "gif"]
                            )
                        ],
                    ),
                ),
                (
                    "date_posted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("duration", models.FloatField(blank=True, null=True)),
                ("unlisted", models.BooleanField(default=False)),
                ("id", models.SlugField(primary_key=True, serialize=False)),
                ("recommendations", models.PositiveIntegerField(default=0)),
                ("push_notification", models.BooleanField(default=True)),
                ("recommendation_milestones", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Memes", "Memes"),
                            ("Gaming", "Gaming"),
                            ("Education", "Education"),
                            ("Animation", "Animation"),
                            ("Entertainment", "Entertainment"),
                            ("Music", "Music"),
                            ("Discussion", "Discussion"),
                            ("Miscellaneous", "Miscellaneous"),
                        ],
                        default="Entertainment",
                        max_length=13,
                    ),
                ),
                (
                    "comments",
                    models.ManyToManyField(
                        blank=True, related_name="video_comments", to="videos.comment"
                    ),
                ),
                (
                    "dislikes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="video_dislikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="video_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
                (
                    "views",
                    models.ManyToManyField(
                        blank=True,
                        related_name="video_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(models.Model, object),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="videos.video"
            ),
        ),
    ]
