# Generated by Django 5.1.1 on 2025-04-26 17:42

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="(must be under 2000 characters)",
                null=True,
                validators=[
                    videos.models.validate_length,
                ],
            ),
        ),
    ]
