# Generated by Django 5.1.1 on 2025-04-26 17:42

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_video_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(
                validators=[
                    videos.models.validate_length,
                ]
            ),
        ),
    ]
