# Generated by Django 5.1.1 on 2025-04-26 17:44

import django.db.models.deletion
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_videos"),
        ("videos", "0003_alter_comment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="commenter",
            field=models.ForeignKey(
                default=1,
                help_text="(must be under 500 characters)",
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="(must be under 500 characters)",
                null=True,
                validators=[
                    videos.models.validate_length,
                ],
            ),
        ),
    ]
