# Generated by Django 5.1.1 on 2025-04-27 07:49

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_alter_comment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(validators=[videos.models.validate_length]),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="(must be under 500 characters)",
                null=True,
                validators=[videos.models.validate_length],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="notification_message",
            field=models.CharField(default="new video", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=75),
        ),
    ]
