# Generated by Django 5.1.1 on 2025-04-27 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_alter_comment_comment_alter_video_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="pinned_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="videos.comment",
            ),
        ),
    ]
