
# Generated by Django 4.1.3 on 2022-11-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_video_video_file_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=75),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]

# Generated by Django 4.1.3 on 2022-11-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_video_video_file_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=75),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]

