
# Generated by Django 4.1.3 on 2022-11-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_options_alter_video_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLOCKED_IPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]

# Generated by Django 4.1.3 on 2022-11-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_options_alter_video_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLOCKED_IPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]

