
# Generated by Django 4.1.3 on 2022-11-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_blocked_ips'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BLOCKED_IPS',
        ),
    ]

# Generated by Django 4.1.3 on 2022-11-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_blocked_ips'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BLOCKED_IPS',
        ),
    ]

