
# Generated by Django 4.1.3 on 2022-11-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_alter_comment_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=150),
        ),
    ]

# Generated by Django 4.1.3 on 2022-11-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_alter_comment_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=150),
        ),
    ]

