
# Generated by Django 4.1.3 on 2022-11-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_alter_comment_options_comment_dislikes_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=250),
        ),
    ]

# Generated by Django 4.1.3 on 2022-11-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_alter_comment_options_comment_dislikes_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=250),
        ),
    ]

