
# Generated by Django 4.1.3 on 2022-11-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_alter_comment_comment_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]

# Generated by Django 4.1.3 on 2022-11-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_alter_comment_comment_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]

