
# Generated by Django 4.1.3 on 2022-11-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]

# Generated by Django 4.1.3 on 2022-11-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]

