
# Generated by Django 4.1.7 on 2023-04-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_alter_video_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]

# Generated by Django 4.1.7 on 2023-04-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_alter_video_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]

