
# Generated by Django 4.1.7 on 2023-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_alter_video_options_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]

# Generated by Django 4.1.7 on 2023-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_alter_video_options_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]

