# Generated by Django 4.2 on 2023-05-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_profile_username'),
        ('videos', '0027_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploader_profile',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
