# Generated by Django 4.2 on 2023-05-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0028_video_uploader_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uploader_profile',
        ),
    ]
