# Generated by Django 4.2.5 on 2023-09-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0031_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
