# Generated by Django 4.2.5 on 2023-09-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0032_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
