# Generated by Django 4.2.5 on 2023-09-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0033_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
