# Generated by Django 4.2.5 on 2023-09-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0035_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=40),
        ),
    ]
