# Generated by Django 5.1.1 on 2024-09-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0046_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='notification_message',
            field=models.CharField(default='new video', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
