# Generated by Django 5.1.1 on 2024-10-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0047_video_notification_message_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
