# Generated by Django 5.1.1 on 2024-10-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0050_comment_replying_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replying_to',
        ),
    ]
