# Generated by Django 5.1.1 on 2024-10-16 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0051_remove_comment_replying_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replying_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='videos.comment'),
        ),
    ]
