# Generated by Django 5.1.1 on 2024-11-24 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0053_remove_comment_passed_milestones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='suggestions',
        ),
        migrations.AddField(
            model_name='video',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='video_recommendations', to=settings.AUTH_USER_MODEL),
        ),
    ]
