# Generated by Django 5.1.1 on 2024-11-25 20:38

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0055_remove_video_recommendations_video_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=200, validators=[videos.models.validate_characters]),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[videos.models.validate_characters]),
        ),
        migrations.AlterField(
            model_name='video',
            name='notification_message',
            field=models.CharField(default='new video', max_length=50, null=True, validators=[videos.models.validate_characters]),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=75, validators=[videos.models.validate_characters]),
        ),
    ]
