# Generated by Django 5.1.1 on 2024-11-26 20:57

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0056_alter_comment_comment_alter_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='video_comments', to='videos.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=500, validators=[videos.models.validate_characters]),
        ),
    ]
