# Generated by Django 5.1.1 on 2024-11-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0058_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='comment_replies', to='videos.comment'),
        ),
    ]
