# Generated by Django 5.1.1 on 2024-12-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0062_video_category_alter_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Memes', 'Memes'), ('Gaming', 'Gaming'), ('Education', 'Education'), ('Animation', 'Animation'), ('Entertainment', 'Entertainment'), ('Music', 'Music'), ('Discussion', 'Discussion'), ('Miscellaneous', 'Miscellaneous')], default='Entertainment', max_length=13),
        ),
    ]
