# Generated by Django 5.1.1 on 2024-12-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0051_personalstyle'),
        ('videos', '0063_alter_video_thumbnail_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='collaborators',
            field=models.ManyToManyField(blank=True, limit_choices_to=5, related_name='video_views', to='profiles.profile'),
        ),
    ]
