# Generated by Django 5.1.1 on 2025-04-28 14:14

import django.db.models.deletion
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0065_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pinned_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(validators=[videos.models.validate_characters]),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='(must be under 500 characters)', null=True, validators=[videos.models.validate_characters]),
        ),
        migrations.AlterField(
            model_name='video',
            name='notification_message',
            field=models.CharField(default='new video', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
