# Generated by Django 5.1.1 on 2024-12-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_alter_profile_profile_picture'),
        ('videos', '0065_alter_video_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='video_collaborators', to='profiles.profile'),
        ),
    ]
