# Generated by Django 5.1.1 on 2025-05-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0066_video_pinned_comment_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
