# Generated by Django 5.1.1 on 2024-12-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0066_alter_video_collaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='collaborators',
        ),
    ]
