# Generated by Django 5.1.1 on 2025-05-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0067_video_recommendation_multiplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="recommendation_multiplier",
        ),
        migrations.AddField(
            model_name="video",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
