# Generated by Django 5.1.1 on 2024-12-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0067_remove_video_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='recommendation_milestones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
