# Generated by Django 5.1.1 on 2025-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0052_remove_profile_recommendations_left"),
        ("videos", "0067_video_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="recommendations",
        ),
        migrations.AddField(
            model_name="video",
            name="recommendations",
            field=models.ManyToManyField(
                blank=True, related_name="video_recommendations", to="profiles.profile"
            ),
        ),
    ]
