# Generated by Django 5.1.1 on 2025-09-27 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0068_remove_video_recommendations_video_recommendations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="pinned_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="videos.comment",
            ),
        ),
    ]
