# Generated by Django 5.1.1 on 2024-12-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0069_video_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='catagory',
            field=models.CharField(choices=[('Memes', 'Memes'), ('Games', 'Gaming'), ('Education', 'Education'), ('Animation', 'Animation'), ('Entertainment', 'Entertainment'), ('Music', 'Music'), ('Discussion', 'Discussion'), ('Misc', 'Miscellanious')], default='Entertainment', max_length=13),
        ),
    ]
