# Generated by Django 5.1.1 on 2024-12-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0071_alter_video_catagory_alter_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='(must between 1kb and 10mb)', upload_to='uploads/thumbnails/'),
        ),
    ]
