# Generated by Django 5.1.1 on 2025-11-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0056_profile_nominated_video"),
        ("videos", "0071_alter_comment_options"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="video",
        #     name="nominations",
        #     field=models.ManyToManyField(
        #         blank=True, related_name="nominations", to="profiles.profile"
        #     ),
        # ),
    ]
