# Generated by Django 5.1.1 on 2026-02-08 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0072_video_nominations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.FileField(
                blank=True,
                help_text="(must be a png or jpg between 1kb and 5mb)",
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "gif"]
                    )
                ],
            ),
        ),
    ]
