# Generated by Django 5.1.1 on 2024-12-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0073_alter_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='catagory',
            new_name='category',
        ),
    ]
