# Generated by Django 5.1.1 on 2026-03-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0062_profile_noms"),
        ("videos", "0073_alter_video_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="nominations",
            field=models.ManyToManyField(
                blank=True, related_name="nominations", to="profiles.profile"
            ),
        ),
    ]
