# Generated by Django 5.1.1 on 2026-04-21 09:48

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0074_video_nominations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="category",
            field=models.CharField(
                choices=[
                    ("Memes", "Memes"),
                    ("Gaming", "Gaming"),
                    ("Education", "Education"),
                    ("Animation", "Animation"),
                    ("Entertainment", "Entertainment"),
                    ("Music", "Music"),
                    ("Discussion", "Discussion"),
                    ("Glomble Gloop", "Glomble Gloop"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                default="Entertainment",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="(must be under 500 characters)",
                validators=[videos.models.validate_characters],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="notification_message",
            field=models.CharField(blank=True, default="new video", max_length=50),
        ),
    ]
