# Generated by Django 5.1.1 on 2026-06-04 15:57

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0076_alter_video_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(
                max_length=1000, validators=[videos.models.validate_characters]
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="(must be under 1000 characters)",
                max_length=1000,
                validators=[videos.models.validate_characters],
            ),
        ),
    ]
