# Generated by Django 5.1.1 on 2026-06-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0077_alter_comment_comment_alter_video_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="category",
            field=models.CharField(
                choices=[
                    ("Art", "Art"),
                    ("Animation", "Animation"),
                    ("Discussion", "Discussion"),
                    ("Education", "Education"),
                    ("Entertainment", "Entertainment"),
                    ("Gaming", "Gaming"),
                    ("Memes", "Memes"),
                    ("Music", "Music"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                default="Entertainment",
                max_length=13,
            ),
        ),
    ]
