# Generated by Django 5.1.1 on 2025-04-25 14:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_made", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ProfileCustomisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Background color in hex.",
                        max_length=7,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#000000", help_text="Text color in hex.", max_length=7
                    ),
                ),
                (
                    "text_shadow_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Text shadow color in hex.",
                        max_length=7,
                    ),
                ),
                (
                    "banner_image",
                    models.FileField(
                        blank=True,
                        help_text="(must be a png or jpg between 1kb and 10mb)",
                        upload_to="profiles/banners/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                (
                    "video_banner",
                    models.FileField(
                        blank=True,
                        help_text="(must be a png or jpg between 1kb and 10mb)",
                        upload_to="profiles/video_banners/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        max_length=1000,
                        validators=[profiles.models.validate_characters],
                    ),
                ),
                ("date_sent", models.DateTimeField(default=django.utils.timezone.now)),
                ("read", models.BooleanField(default=False)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="profiles.chat"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chat",
            name="messages",
            field=models.ManyToManyField(
                related_name="messages", to="profiles.message"
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "bio",
                    models.TextField(
                        default="hello, world!",
                        max_length=500,
                        validators=[profiles.models.validate_characters],
                    ),
                ),
                (
                    "profile_picture",
                    models.FileField(
                        blank=True,
                        default="profiles/pfps/default.png",
                        help_text="(must be a png or jpg between 1kb and 10mb)",
                        upload_to="media/profiles/pfps/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                ("date_made", models.DateTimeField(default=django.utils.timezone.now)),
                ("follower_milestones", models.PositiveIntegerField(default=0)),
                ("id", models.SlugField(primary_key=True, serialize=False)),
                ("recommendations_left", models.PositiveIntegerField(default=3)),
                ("ratings", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "rating",
                    models.FloatField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("moderator", models.BooleanField(default=False)),
                ("helper", models.BooleanField(default=False)),
                ("shadowbanned", models.BooleanField(default=False)),
                (
                    "chats",
                    models.ManyToManyField(
                        blank=True, related_name="chats", to="profiles.chat"
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        related_name="followers", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "notifications",
                    models.ManyToManyField(
                        blank=True,
                        related_name="notifications",
                        to="notifications.basenotification",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
