# Generated by Django 5.1.1 on 2025-04-25 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="watched_videos",
            field=models.ManyToManyField(
                blank=True, related_name="watched_videos", to="videos.video"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="members",
            field=models.ManyToManyField(related_name="members", to="profiles.profile"),
        ),
        migrations.AddField(
            model_name="profilecustomisation",
            name="customised_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="customisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profilecustomisation",
            ),
        ),
    ]
