# Generated by Django 4.1.3 on 2022-11-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pfp',
            new_name='profile_picture',
        ),
    ]
