# Generated by Django 5.1.1 on 2025-04-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="videos",
            field=models.ManyToManyField(
                blank=True, related_name="videos", to="videos.video"
            ),
        ),
    ]
