# Generated by Django 4.1.3 on 2022-11-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profiles/pfps/default.webp', upload_to='profiles/pfps/'),
        ),
    ]
