# Generated by Django 5.1.1 on 2025-04-26 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilecustomisation",
            name="background_image",
            field=models.FileField(
                blank=True,
                help_text="(must be a png or jpg between 1kb and 10mb)",
                upload_to="profiles/backgrounds/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
