# Generated by Django 5.1.1 on 2025-04-26 19:41

import django.core.validators
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profilecustomisation_background_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilecustomisation",
            name="background_image",
            field=models.FileField(
                blank=True,
                help_text="(this won't show up for anyone else)",
                upload_to="profiles/backgrounds/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    ),
                    profiles.models.validate_filesize,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profilecustomisation",
            name="banner_image",
            field=models.FileField(
                blank=True,
                upload_to="profiles/banners/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    ),
                    profiles.models.validate_filesize,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profilecustomisation",
            name="video_banner",
            field=models.FileField(
                blank=True,
                upload_to="profiles/video_banners/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    ),
                    profiles.models.validate_filesize,
                ],
            ),
        ),
    ]
