# Generated by Django 4.1.3 on 2022-11-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='videos',
            field=models.IntegerField(default=0),
        ),
    ]
