# Generated by Django 5.1.1 on 2025-04-26 20:39

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profilecustomisation_background_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilecustomisation",
            name="background_image",
        ),
        migrations.AlterField(
            model_name="profilecustomisation",
            name="banner_image",
            field=models.FileField(
                blank=True,
                upload_to="profiles/banners/",
                validators=[
                    profiles.models.validate_filesize,
                    profiles.models.validate_image,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profilecustomisation",
            name="video_banner",
            field=models.FileField(
                blank=True,
                upload_to="profiles/video_banners/",
                validators=[
                    profiles.models.validate_filesize,
                    profiles.models.validate_image,
                ],
            ),
        ),
    ]
