# Generated by Django 5.1.1 on 2025-04-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_remove_profilecustomisation_background_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilecustomisation",
            name="background_color",
            field=models.CharField(
                default="#ffffff", help_text="Background colour in hex.", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="profilecustomisation",
            name="text_color",
            field=models.CharField(
                default="#000000", help_text="Text colour in hex.", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="profilecustomisation",
            name="text_shadow_color",
            field=models.CharField(
                default="#ffffff", help_text="Text shadow colour in hex.", max_length=7
            ),
        ),
    ]
