# Generated by Django 5.1.1 on 2025-04-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_profilecustomisation_background_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilecustomisation",
            name="video_card_text_color",
            field=models.CharField(
                default="#000000",
                help_text="Video card text colour in hex.",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="profilecustomisation",
            name="video_card_text_shadow_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Video card text shadow colour in hex.",
                max_length=7,
            ),
        ),
    ]
