# Generated by Django 5.1.1 on 2024-09-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_profile_bio_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/pfps/default.png', null=True, upload_to='profiles/pfps/'),
        ),
    ]
