# Generated by Django 5.1.1 on 2024-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profiles/pfps/default.png', null=True, upload_to='media/profiles/pfps/'),
        ),
    ]
