# Generated by Django 5.1.1 on 2024-10-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passed_milestones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
