# Generated by Django 5.1.1 on 2024-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_alter_chat_id_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(null=True, related_name='messages', to='profiles.message'),
        ),
    ]
