# Generated by Django 5.1.1 on 2024-10-11 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_message_read_alter_message_sender'),
        ('videos', '0049_comment_passed_milestones_video_passed_milestones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='using_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfileActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_profiles', models.ManyToManyField(related_name='followed_profiles', to='profiles.profile')),
                ('liked_videos', models.ManyToManyField(related_name='liked_videos', to='videos.video')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('viewed_videos', models.ManyToManyField(related_name='viewed_videos', to='videos.video')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='profiles.profileactivity'),
        ),
    ]
