# Generated by Django 5.1.1 on 2024-11-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_profileactivity_disliked_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='using_activity',
        ),
        migrations.DeleteModel(
            name='ProfileActivity',
        ),
    ]
