# Generated by Django 5.1.1 on 2024-11-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_remove_basenotification_like_notification_and_more'),
        ('profiles', '0034_remove_profile_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.ManyToManyField(null=True, related_name='notifications', to='notifications.basenotification'),
        ),
    ]
