# Generated by Django 5.1.1 on 2024-11-25 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_remove_basenotification_like_notification_and_more'),
        ('profiles', '0034_remove_profile_activity_and_more'),
        ('videos', '0053_remove_comment_passed_milestones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_recommend',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 1, 1)),
        ),
    ]
