# Generated by Django 5.1.1 on 2024-11-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_remove_basenotification_like_notification_and_more'),
        ('profiles', '0035_profile_chats_profile_last_recommend_and_more'),
        ('videos', '0054_remove_video_suggestions_video_recommendations'),
    ]

    operations = [
    ]
