# Generated by Django 5.1.1 on 2024-11-26 11:13

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_remove_basenotification_like_notification_and_more'),
        ('profiles', '0036_profile_chats_profile_notifications_and_more'),
        ('videos', '0056_alter_comment_comment_alter_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(validators=[profiles.models.validate_characters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='hello, world!', max_length=300, validators=[profiles.models.validate_characters]),
        ),
    ]
