# Generated by Django 5.1.1 on 2024-11-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_profile_watched_videos'),
        ('videos', '0054_remove_video_suggestions_video_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chats',
            field=models.ManyToManyField(related_name='chats', to='profiles.chat'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watched_videos',
            field=models.ManyToManyField(related_name='watched_videos', to='videos.video'),
        ),
    ]
