# Generated by Django 5.1.1 on 2024-11-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_alter_profile_notifications'),
        ('profiles', '0037_profile_chats_profile_notifications_profile_rating_and_more'),
    ]

    operations = [
    ]
