# Generated by Django 5.1.1 on 2024-11-24 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_profile_chats_alter_profile_watched_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_recommend',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 1, 0)),
        ),
    ]
