# Generated by Django 5.1.1 on 2024-11-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_profile_chats_profile_watched_videos_and_more'),
        ('videos', '0059_remove_comment_reply_comment_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_recommend',
        ),
        migrations.AddField(
            model_name='profile',
            name='recommendations_left',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
