# Generated by Django 5.1.1 on 2024-11-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_remove_profile_last_recommend_profile_chats_and_more'),
        ('videos', '0059_remove_comment_reply_comment_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chats',
            field=models.ManyToManyField(blank=True, related_name='chats', to='profiles.chat'),
        ),
        migrations.AddField(
            model_name='profile',
            name='watched_videos',
            field=models.ManyToManyField(blank=True, related_name='watched_videos', to='videos.video'),
        ),
    ]
