# Generated by Django 5.1.1 on 2024-12-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_profile_chats_profile_watched_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='helper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
