# Generated by Django 5.1.1 on 2024-11-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_alter_profile_last_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chats',
            field=models.ManyToManyField(blank=True, related_name='chats', to='profiles.chat'),
        ),
    ]
