# Generated by Django 5.1.1 on 2024-12-03 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0042_profile_helper_profile_moderator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='passed_milestones',
            new_name='follower_milestones',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, default='media/profiles/pfps/default.png', help_text='(must be a png or jpg between 1kb and 10mb)', upload_to='media/profiles/pfps/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
