# Generated by Django 5.1.1 on 2024-11-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_remove_basenotification_like_notification_and_more'),
        ('profiles', '0042_alter_profile_chats'),
        ('videos', '0055_remove_video_recommendations_video_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='notifications.basenotification'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watched_videos',
            field=models.ManyToManyField(blank=True, related_name='watched_videos', to='videos.video'),
        ),
    ]
