# Generated by Django 5.1.1 on 2024-11-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_alter_profile_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
