# Generated by Django 5.1.1 on 2024-12-07 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_profile_ratings_profile_shadowbanned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecustomisation',
            name='video_banner',
            field=models.FileField(blank=True, help_text='(must be a png or jpg between 1kb and 10mb)', upload_to='profiles/video_banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
