# Generated by Django 5.1.1 on 2024-11-25 20:38

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_alter_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(validators=[profiles.models.validate_characters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='hello, world!', max_length=300, validators=[profiles.models.validate_characters]),
        ),
    ]
