# Generated by Django 5.1.1 on 2025-04-28 14:14

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_profilecustomisation_text_shadow_color'),
        ('videos', '0066_video_pinned_comment_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos', to='videos.video'),
        ),
        migrations.AddField(
            model_name='profilecustomisation',
            name='video_card_text_color',
            field=models.CharField(default='#000000', help_text='Video card text colour in hex.', max_length=7),
        ),
        migrations.AddField(
            model_name='profilecustomisation',
            name='video_card_text_shadow_color',
            field=models.CharField(default='#ffffff', help_text='Video card text shadow colour in hex.', max_length=7),
        ),
        migrations.AlterField(
            model_name='profilecustomisation',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Background colour in hex.', max_length=7),
        ),
        migrations.AlterField(
            model_name='profilecustomisation',
            name='banner_image',
            field=models.FileField(blank=True, upload_to='profiles/banners/', validators=[profiles.models.validate_filesize, profiles.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='profilecustomisation',
            name='text_color',
            field=models.CharField(default='#000000', help_text='Text colour in hex.', max_length=7),
        ),
        migrations.AlterField(
            model_name='profilecustomisation',
            name='text_shadow_color',
            field=models.CharField(default='#ffffff', help_text='Text shadow colour in hex.', max_length=7),
        ),
        migrations.AlterField(
            model_name='profilecustomisation',
            name='video_banner',
            field=models.FileField(blank=True, upload_to='profiles/video_banners/', validators=[profiles.models.validate_filesize, profiles.models.validate_image]),
        ),
    ]
