# Generated by Django 5.1.1 on 2024-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_alter_message_message_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_recommend',
        ),
        migrations.AddField(
            model_name='profile',
            name='recommendations_left',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
