# Generated by Django 5.1.1 on 2025-02-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_profilecustomisation_text_shadow_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecustomisation',
            name='text_shadow_color',
            field=models.CharField(default='#ffffff', help_text='Text shadow color in hex.', max_length=7),
        ),
    ]
