# Generated by Django 5.1.1 on 2025-04-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0048_profile_videos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilecustomisation",
            name="background_color",
            field=models.CharField(blank=True, default="#ffffff", max_length=7),
        ),
        migrations.AlterField(
            model_name="profilecustomisation",
            name="text_color",
            field=models.CharField(blank=True, default="#000000", max_length=7),
        ),
        migrations.AlterField(
            model_name="profilecustomisation",
            name="text_shadow_color",
            field=models.CharField(blank=True, default="#ffffff", max_length=7),
        ),
        migrations.AlterField(
            model_name="profilecustomisation",
            name="video_card_text_color",
            field=models.CharField(blank=True, default="#000000", max_length=7),
        ),
        migrations.AlterField(
            model_name="profilecustomisation",
            name="video_card_text_shadow_color",
            field=models.CharField(blank=True, default="#ffffff", max_length=7),
        ),
    ]
