# Generated by Django 5.1.1 on 2024-11-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0048_remove_profile_last_recommend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='helper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
