# Generated by Django 5.1.1 on 2025-05-01 22:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0049_alter_profilecustomisation_background_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recommendations_left',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profilecustomisation',
            name='background_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='profilecustomisation',
            name='text_color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='profilecustomisation',
            name='text_shadow_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='profilecustomisation',
            name='video_card_text_color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='profilecustomisation',
            name='video_card_text_shadow_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7),
        ),
        migrations.CreateModel(
            name='ProfileRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rated_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_ratings', to='profiles.profile')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rater', 'rated_profile')},
            },
        ),
    ]
