# Generated by Django 5.1.1 on 2025-04-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0049_alter_profilecustomisation_background_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="recommendations_left",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
