# Generated by Django 5.1.1 on 2024-12-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0050_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#ffffff', max_length=7)),
                ('secondary_color', models.CharField(default='#000000', max_length=7)),
                ('font_family', models.CharField(default="'Segoe UI', Tahoma, Geneva, Verdana, sans-serif", max_length=255)),
                ('custom_css', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
