# Generated by Django 5.1.1 on 2025-05-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0051_auto_20250501_2214"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="recommendations_left",
        ),
    ]
