# Generated by Django 5.1.1 on 2024-12-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0051_personalstyle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalStyle',
        ),
    ]
