# Generated by Django 5.1.1 on 2025-09-27 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0052_remove_profile_recommendations_left"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
