# Generated by Django 5.1.1 on 2025-09-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0053_alter_profile_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="ratings",
        ),
    ]
