# Generated by Django 5.1.1 on 2024-12-05 20:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0054_rename_passed_milestones_profile_follower_milestones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#ffffff', help_text='Background color in HEX.', max_length=7)),
                ('text_color', models.CharField(default='#000000', help_text='Text color in HEX.', max_length=7)),
                ('banner_image', models.FileField(blank=True, help_text='(must be a png or jpg between 1kb and 10mb)', upload_to='media/profiles/banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('custom_html', models.TextField(blank=True, help_text='Custom HTML for your profile.')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customised_profile', to='profiles.profile')),
            ],
        ),
    ]
