# Generated by Django 5.1.1 on 2024-12-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0055_profilecustomization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecustomization',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Background color in hex.', max_length=7),
        ),
        migrations.AlterField(
            model_name='profilecustomization',
            name='text_color',
            field=models.CharField(default='#000000', help_text='Text color in hex.', max_length=7),
        ),
    ]
