# Generated by Django 5.1.1 on 2024-12-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0056_alter_profilecustomization_background_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileCustomization',
            new_name='ProfileCustomisation',
        ),
    ]
