# Generated by Django 5.1.1 on 2025-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0057_profile_nominated_profile_and_more"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="profile",
        #     name="noms",
        #     field=models.ManyToManyField(
        #         blank=True, related_name="profile_nominations", to="profiles.profile"
        #     ),
        # ),
    ]
