# Generated by Django 5.1.1 on 2026-02-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0058_profile_noms"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilecustomisation",
            name="accent_color",
            field=models.CharField(blank=True, default="#000000", max_length=7),
        ),
    ]
