# Generated by Django 5.1.1 on 2024-12-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0059_profile_shadowbanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecustomisation',
            name='custom_html',
        ),
    ]
