# Generated by Django 5.1.1 on 2026-03-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0060_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
