# Generated by Django 5.1.1 on 2024-12-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0060_remove_profilecustomisation_custom_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.AddField(
            model_name='profile',
            name='ratings',
            field=models.JSONField(default=dict),
        ),
    ]
