# Generated by Django 5.1.1 on 2026-03-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0061_remove_profile_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="noms",
            field=models.ManyToManyField(
                blank=True, related_name="profile_nominations", to="profiles.profile"
            ),
        ),
    ]
