# Generated by Django 5.1.1 on 2026-03-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0062_profile_noms"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followed_profiles", to="profiles.profile"
            ),
        ),
    ]
