# Generated by Django 5.1.1 on 2026-03-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0063_profile_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="banned",
            field=models.BooleanField(default=False),
        ),
    ]
