# Generated by Django 5.1.1 on 2024-12-06 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0064_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecustomisation',
            name='banner_image',
            field=models.FileField(blank=True, help_text='(must be a png or jpg between 1kb and 10mb)', upload_to='profiles/banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
