# Generated by Django 5.1.1 on 2026-03-31 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0064_profile_banned"),
        ("videos", "0074_video_nominations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nominated_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nominated_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="videos.video",
            ),
        ),
    ]
