# Generated by Django 5.1.1 on 2026-03-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0065_alter_profile_nominated_profile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("description", models.TextField(max_length=1000)),
                ("associated_ips", models.TextField()),
                (
                    "associated_profiles",
                    models.ManyToManyField(
                        related_name="associated_profiles", to="profiles.profile"
                    ),
                ),
            ],
        ),
    ]
