# Generated by Django 5.1.1 on 2026-03-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0066_bans"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bans",
            new_name="Ban",
        ),
    ]
