# Generated by Django 5.1.1 on 2026-03-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0067_rename_bans_ban"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ban",
            name="associated_ips",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="ban",
            name="associated_profiles",
            field=models.ManyToManyField(
                blank=True, related_name="associated_profiles", to="profiles.profile"
            ),
        ),
    ]
