# Generated by Django 5.1.1 on 2026-03-31 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0068_alter_ban_associated_ips_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BanAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appeal_message", models.TextField(max_length=5000)),
                (
                    "ban",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="profiles.ban"
                    ),
                ),
            ],
        ),
    ]
