# Generated by Django 5.1.1 on 2026-03-31 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0069_banappeal"),
    ]

    operations = [
        migrations.AddField(
            model_name="ban",
            name="date_made",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="banappeal",
            name="date_made",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
