# Generated by Django 5.1.1 on 2026-04-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0070_ban_date_made_banappeal_date_made"),
    ]

    operations = [
        migrations.AddField(
            model_name="ban",
            name="appeals",
            field=models.ManyToManyField(
                blank=True, related_name="notifications", to="profiles.banappeal"
            ),
        ),
    ]
