# Generated by Django 5.1.1 on 2026-04-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0071_ban_appeals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ban",
            name="associated_ips",
        ),
        migrations.AlterField(
            model_name="ban",
            name="appeals",
            field=models.ManyToManyField(
                blank=True, related_name="appeals", to="profiles.banappeal"
            ),
        ),
    ]
