# Generated by Django 5.1.1 on 2026-06-03 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0072_remove_ban_associated_ips_alter_ban_appeals"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("description", models.TextField(max_length=1000)),
                ("date_made", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "associated_profiles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="associated_profiles_warning",
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="warnings",
            field=models.ManyToManyField(blank=True, to="profiles.warning"),
        ),
    ]
