# Generated by Django 5.1.1 on 2026-06-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0073_warning_profile_warnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="ban",
            name="given_reason",
            field=models.TextField(default="a", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warning",
            name="given_reason",
            field=models.TextField(default="a", max_length=1000),
            preserve_default=False,
        ),
    ]
