# Generated by Django 5.1.1 on 2026-06-04 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0074_ban_given_reason_warning_given_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ban",
            name="associated_profiles",
        ),
        migrations.RemoveField(
            model_name="ban",
            name="name",
        ),
        migrations.RemoveField(
            model_name="warning",
            name="associated_profiles",
        ),
        migrations.RemoveField(
            model_name="warning",
            name="name",
        ),
        migrations.AddField(
            model_name="ban",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warning",
            name="profile",
            field=models.ForeignKey(
                default="a",
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ban",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="warnings",
            field=models.ManyToManyField(
                blank=True, related_name="profile_warnings", to="profiles.warning"
            ),
        ),
        migrations.AlterField(
            model_name="warning",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
