# Generated by Django 5.1.1 on 2026-06-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0075_remove_ban_associated_profiles_remove_ban_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ban",
            name="ban_giver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ban_giver",
                to="profiles.profile",
            ),
        ),
    ]
