# Generated by Django 5.1.1 on 2026-06-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0076_ban_ban_giver"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="superadmin",
            field=models.BooleanField(default=False),
        ),
    ]
