# Generated by Django 5.1.1 on 2026-06-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0077_profile_superadmin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="helper",
        ),
    ]
