# Generated by Django 5.1.1 on 2026-06-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0078_remove_profile_helper"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="superadmin",
        ),
    ]
