# Generated by Django 5.1.1 on 2026-06-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0079_remove_profile_superadmin"),
        ("videos", "0077_alter_comment_comment_alter_video_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="comments", to="videos.comment"
            ),
        ),
        migrations.AlterField(
            model_name="ban",
            name="given_reason",
            field=models.TextField(
                help_text="(this will be displayed to the user)", max_length=1000
            ),
        ),
    ]
