# Generated by Django 5.1.1 on 2026-06-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0080_profile_comments_alter_ban_given_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="ban",
            name="delete_all_creations",
            field=models.BooleanField(default=True),
        ),
    ]
