# Generated by Django 5.1.1 on 2026-06-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0081_ban_delete_all_creations"),
    ]

    operations = [
        migrations.AddField(
            model_name="banappeal",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ban",
            name="delete_all_creations",
            field=models.BooleanField(
                default=True,
                help_text="This permanently deletes everything but their account (videos, comments, given ratings, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="ban",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="(this will only show for you and other admins)",
                max_length=1000,
            ),
        ),
    ]
