# Generated by Django 5.1.1 on 2026-06-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0082_banappeal_status_alter_ban_delete_all_creations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banappeal",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
