# Generated by Django 5.1.1 on 2026-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0083_banappeal_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banappeal",
            name="status",
        ),
        migrations.AddField(
            model_name="banappeal",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
    ]
