# Generated by Django 5.1.1 on 2026-06-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0084_remove_banappeal_status_banappeal_rejected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilecustomisation",
            name="text_shadow_color",
            field=models.CharField(blank=True, default="#ffffff", max_length=9),
        ),
    ]
