# Generated by Django 5.1.1 on 2026-06-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0085_alter_profilecustomisation_text_shadow_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilecustomisation",
            name="use_text_shadow",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profilecustomisation",
            name="use_video_card_text_shadow",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="profilecustomisation",
            name="text_shadow_color",
            field=models.CharField(blank=True, default="#ffffff", max_length=7),
        ),
    ]
