# Generated by Django 5.1.1 on 2026-06-27 22:42

import django.core.validators
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0086_profilecustomisation_use_text_shadow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.FileField(
                blank=True,
                default="profiles/pfps/default.png",
                help_text="(must be a png or jpg between 1kb and 10mb)",
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    ),
                    profiles.models.validate_filesize,
                    profiles.models.validate_image,
                ],
            ),
        ),
    ]
