# Generated by Django 5.1.1 on 2026-06-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0087_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="warnings",
        ),
        migrations.DeleteModel(
            name="Warning",
        ),
    ]
