# Generated by Django 5.1.1 on 2026-06-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0088_remove_profile_warnings_delete_warning"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilecustomisation",
            name="use_accent",
            field=models.BooleanField(default=True),
        ),
    ]
