cp -r /home/a/Downloads/eniv/secret_key.txt .
cp -r /home/a/Downloads/eniv/email_pass.txt .
cp -r /home/a/Downloads/eniv/email.txt .
cp -r /home/a/Downloads/eniv/ca.crt .
cp -r /home/a/Downloads/eniv/ca.key .
cp -r /home/a/Downloads/eniv/client.crt .
cp -r /home/a/Downloads/eniv/client.csr .
cp -r /home/a/Downloads/eniv/client.key .
cp -r /home/a/Downloads/eniv/client.p12 .
cp -r /home/a/Downloads/eniv/glomble.crt .
cp -r /home/a/Downloads/eniv/glomble.csr .
cp -r /home/a/Downloads/eniv/glomble.key .
cp -r /home/a/Downloads/eniv/db.sqlite3 .
cp -r /home/a/Downloads/eniv/conf/ .
cp -r /home/a/Downloads/eniv/media/ .
cp -r /home/a/Downloads/eniv/config/ .
