# Generated by Django 4.2.5 on 2023-09-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoreport',
            old_name='report',
            new_name='reasoning',
        ),
    ]
