# Generated by Django 4.2.5 on 2023-09-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_report_videoreport_reasoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilereport',
            name='brief_summary',
            field=models.TextField(default='trole', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoreport',
            name='brief_summary',
            field=models.TextField(default='trole', max_length=30),
            preserve_default=False,
        ),
    ]
