# Generated by Django 4.2.5 on 2023-09-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_profilereport_brief_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilereport',
            old_name='report',
            new_name='reasoning',
        ),
    ]
