# Generated by Django 5.1.1 on 2024-11-25 21:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_report_profilereport_reasoning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilereport',
            name='brief_summary',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profilereport',
            name='reasoning',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='videoreport',
            name='brief_summary',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videoreport',
            name='reasoning',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_summary', models.TextField(max_length=50)),
                ('explanation', models.TextField(max_length=500)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_sent'],
            },
        ),
    ]
