# Generated by Django 5.1.1 on 2024-09-28 15:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0024_alter_profile_profile_picture'),
        ('videos', '0047_video_notification_message_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='added peanut butter sandwiches', max_length=200, null=True)),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(models.Model, object),
        ),
        migrations.CreateModel(
            name='BaseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('date_notified', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            bases=(models.Model, object),
        ),
        migrations.CreateModel(
            name='VideoNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='greg bog', max_length=200, null=True)),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_profiles', models.ManyToManyField(blank=True, related_name='notified_profiles', through='notifications.BaseNotification', to='profiles.profile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            bases=(models.Model, object),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.videonotification'),
        ),
    ]
