# Generated by Django 5.1.1 on 2025-04-25 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                (
                    "date_notified",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            bases=(models.Model, object),
        ),
        migrations.CreateModel(
            name="CommentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        default="Someone just commented on your video",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("date_made", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(models.Model, object),
        ),
        migrations.CreateModel(
            name="MilestoneNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        default="You reached a new follower milestone!",
                        max_length=75,
                        null=True,
                    ),
                ),
                ("date_made", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(models.Model, object),
        ),
        migrations.CreateModel(
            name="UpdateNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        default="added peanut butter sandwiches",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("date_made", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(models.Model, object),
        ),
        migrations.CreateModel(
            name="VideoNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(default="greg bog", max_length=50, null=True),
                ),
                ("date_made", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(models.Model, object),
        ),
    ]
