# Generated by Django 5.1.1 on 2024-12-08 21:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
        ('videos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('date_notified', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            bases=(models.Model, object),
        ),
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Someone just commented on your video', max_length=50, null=True)),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.comment')),
                ('notified_profiles', models.ManyToManyField(blank=True, through='notifications.BaseNotification', to='profiles.profile')),
            ],
            bases=(models.Model, object),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='comment_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.commentnotification'),
        ),
        migrations.CreateModel(
            name='MilestoneNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='You reached a new follower milestone!', max_length=75, null=True)),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_profiles', models.ManyToManyField(blank=True, through='notifications.BaseNotification', to='profiles.profile')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone_profile', to='profiles.profile')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone_video', to='videos.video')),
            ],
            bases=(models.Model, object),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='milestone_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.milestonenotification'),
        ),
        migrations.CreateModel(
            name='UpdateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='added peanut butter sandwiches', max_length=200, null=True)),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_profiles', models.ManyToManyField(blank=True, through='notifications.BaseNotification', to='profiles.profile')),
            ],
            bases=(models.Model, object),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='update_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.updatenotification'),
        ),
        migrations.CreateModel(
            name='VideoNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='greg bog', max_length=50, null=True)),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_profiles', models.ManyToManyField(blank=True, through='notifications.BaseNotification', to='profiles.profile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            bases=(models.Model, object),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='video_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.videonotification'),
        ),
    ]
