# Generated by Django 5.1.1 on 2024-10-09 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('profiles', '0024_alter_profile_profile_picture'),
        ('videos', '0047_video_notification_message_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Someone just commented on your video', max_length=200, null=True)),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.comment')),
                ('notified_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            bases=(models.Model, object),
        ),
    ]
