# Generated by Django 5.1.1 on 2025-04-25 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        ("profiles", "0001_initial"),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basenotification",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.profile"
            ),
        ),
        migrations.AddField(
            model_name="commentnotification",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="videos.comment"
            ),
        ),
        migrations.AddField(
            model_name="commentnotification",
            name="notified_profiles",
            field=models.ManyToManyField(
                blank=True,
                through="notifications.BaseNotification",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="basenotification",
            name="comment_notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.commentnotification",
            ),
        ),
        migrations.AddField(
            model_name="milestonenotification",
            name="notified_profiles",
            field=models.ManyToManyField(
                blank=True,
                through="notifications.BaseNotification",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="milestonenotification",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestone_profile",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="milestonenotification",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestone_video",
                to="videos.video",
            ),
        ),
        migrations.AddField(
            model_name="basenotification",
            name="milestone_notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.milestonenotification",
            ),
        ),
        migrations.AddField(
            model_name="updatenotification",
            name="notified_profiles",
            field=models.ManyToManyField(
                blank=True,
                through="notifications.BaseNotification",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="basenotification",
            name="update_notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.updatenotification",
            ),
        ),
        migrations.AddField(
            model_name="videonotification",
            name="notified_profiles",
            field=models.ManyToManyField(
                blank=True,
                through="notifications.BaseNotification",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="videonotification",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="videos.video"
            ),
        ),
        migrations.AddField(
            model_name="basenotification",
            name="video_notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.videonotification",
            ),
        ),
    ]
