# Generated by Django 5.1.1 on 2024-10-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_commentnotification'),
        ('profiles', '0024_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basenotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='commentnotification',
            name='notified_profile',
        ),
        migrations.AddField(
            model_name='basenotification',
            name='comment_notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.commentnotification'),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='video_notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.videonotification'),
        ),
        migrations.AddField(
            model_name='commentnotification',
            name='notified_profiles',
            field=models.ManyToManyField(blank=True, through='notifications.BaseNotification', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='videonotification',
            name='notified_profiles',
            field=models.ManyToManyField(blank=True, through='notifications.BaseNotification', to='profiles.profile'),
        ),
    ]
