# Generated by Django 5.1.1 on 2024-10-09 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_basenotification_notification_and_more'),
        ('profiles', '0024_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotification',
            name='update_notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.updatenotification'),
        ),
        migrations.AddField(
            model_name='updatenotification',
            name='notified_profiles',
            field=models.ManyToManyField(blank=True, through='notifications.BaseNotification', to='profiles.profile'),
        ),
    ]
