# Generated by Django 5.1.1 on 2024-10-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_basenotification_update_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentnotification',
            name='message',
            field=models.CharField(default='Someone just commented on your video', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videonotification',
            name='message',
            field=models.CharField(default='greg bog', max_length=50, null=True),
        ),
    ]
