# Generated by Django 5.1.1 on 2024-10-10 06:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_commentnotification_message_and_more'),
        ('profiles', '0024_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Started following you', max_length=75, null=True)),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_profiles', models.ManyToManyField(blank=True, through='notifications.BaseNotification', to='profiles.profile')),
            ],
            bases=(models.Model, object),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='follow_notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.follownotification'),
        ),
        migrations.CreateModel(
            name='LikeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Liked your post', max_length=75, null=True)),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_profiles', models.ManyToManyField(blank=True, through='notifications.BaseNotification', to='profiles.profile')),
            ],
            bases=(models.Model, object),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='like_notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.likenotification'),
        ),
    ]
