# Generated by Django 5.1.1 on 2024-10-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_follownotification_and_more'),
        ('profiles', '0025_profile_passed_milestones'),
        ('videos', '0049_comment_passed_milestones_video_passed_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='follownotification',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone_profile', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='likenotification',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.comment'),
        ),
        migrations.AddField(
            model_name='likenotification',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
        migrations.AlterField(
            model_name='follownotification',
            name='message',
            field=models.CharField(default='You reached a new follower milestone!', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='likenotification',
            name='message',
            field=models.CharField(default='Someone liked your post', max_length=75, null=True),
        ),
    ]
