# Generated by Django 5.1.1 on 2024-10-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_follownotification_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likenotification',
            name='comment',
        ),
    ]
