# Generated by Django 5.1.1 on 2024-10-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_remove_likenotification_comment'),
        ('profiles', '0025_profile_passed_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='follownotification',
            name='follower',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='profiles.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likenotification',
            name='liker',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='profiles.profile'),
            preserve_default=False,
        ),
    ]
