# Generated by Django 5.1.1 on 2024-10-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_remove_follownotification_follower_and_more'),
        ('profiles', '0025_profile_passed_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='follownotification',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='likenotification',
            name='liker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='profiles.profile'),
        ),
    ]
