# Generated by Django 5.1.1 on 2024-10-11 07:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_follownotification_follower_likenotification_liker'),
        ('profiles', '0029_alter_chat_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Has sent you a message', max_length=75, null=True)),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='profiles.message')),
                ('notified_profiles', models.ManyToManyField(blank=True, through='notifications.BaseNotification', to='profiles.profile')),
            ],
            bases=(models.Model, object),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='message_notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.messagenotification'),
        ),
    ]
