# Generated by Django 5.1.1 on 2024-10-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_remove_basenotification_message_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenotification',
            name='comment_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.commentnotification'),
        ),
        migrations.AlterField(
            model_name='basenotification',
            name='follow_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.follownotification'),
        ),
        migrations.AlterField(
            model_name='basenotification',
            name='like_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.likenotification'),
        ),
        migrations.AlterField(
            model_name='basenotification',
            name='update_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.updatenotification'),
        ),
        migrations.AlterField(
            model_name='basenotification',
            name='video_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.videonotification'),
        ),
    ]
