# Generated by Django 5.1.1 on 2024-11-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_alter_basenotification_comment_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basenotification',
            name='like_notification',
        ),
        migrations.DeleteModel(
            name='LikeNotification',
        ),
    ]
