# Generated by Django 5.1.1 on 2024-12-03 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_remove_basenotification_like_notification_and_more'),
        ('profiles', '0054_rename_passed_milestones_profile_follower_milestones'),
        ('videos', '0068_video_recommendation_milestones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basenotification',
            name='follow_notification',
        ),
        migrations.CreateModel(
            name='MilestoneNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='You reached a new follower milestone!', max_length=75, null=True)),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_profiles', models.ManyToManyField(blank=True, through='notifications.BaseNotification', to='profiles.profile')),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone_profile', to='profiles.profile')),
                ('video', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone_profile', to='videos.video')),
            ],
            bases=(models.Model, object),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='milestone_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.milestonenotification'),
        ),
        migrations.DeleteModel(
            name='FollowNotification',
        ),
    ]
