# Generated by Django 5.1.1 on 2024-12-04 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_remove_basenotification_follow_notification_and_more'),
        ('profiles', '0043_rename_passed_milestones_profile_follower_milestones_and_more'),
        ('videos', '0061_video_recommendation_milestones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonenotification',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone_profile', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='milestonenotification',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone_profile', to='videos.video'),
        ),
    ]
