# Generated by Django 5.1.1 on 2024-12-06 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_remove_basenotification_follow_notification_and_more'),
        ('videos', '0070_alter_video_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonenotification',
            name='video',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone_video', to='videos.video'),
        ),
    ]
