# Generated by Django 5.1.1 on 2024-12-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_alter_milestonenotification_video'),
        ('profiles', '0060_remove_profilecustomisation_custom_html'),
        ('videos', '0070_alter_video_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonenotification',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone_profile', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='milestonenotification',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone_video', to='videos.video'),
        ),
    ]
