# Generated by Django 5.1.1 on 2025-02-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_alter_milestonenotification_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentnotification',
            name='special_reply',
            field=models.BooleanField(default=False),
        ),
    ]
