# Generated by Django 5.1.1 on 2025-10-23 19:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0021_alter_milestonenotification_video"),
        # ("profiles", "0055_alter_profile_followers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basenotification",
            options={"ordering": ["priority_level"]},
        ),
        migrations.AddField(
            model_name="basenotification",
            name="priority_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="basenotification",
            name="requires_action",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="videonotification",
            name="message",
            field=models.CharField(default="greg bog", max_length=75, null=True),
        ),
        migrations.CreateModel(
            name="MiscellaneousNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        default="hi i'm a placeholder nice to meet you",
                        max_length=75,
                        null=True,
                    ),
                ),
                ("date_made", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "notified_profiles",
                    models.ManyToManyField(
                        blank=True,
                        through="notifications.BaseNotification",
                        to="profiles.profile",
                    ),
                ),
            ],
            bases=(models.Model, object),
        ),
        migrations.AddField(
            model_name="basenotification",
            name="miscellaneous_notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.miscellaneousnotification",
            ),
        ),
    ]
