# Generated by Django 5.1.1 on 2025-02-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_commentnotification_special_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentnotification',
            name='special_reply',
        ),
    ]
