# Generated by Django 5.1.1 on 2024-12-08 21:26

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_money', models.PositiveIntegerField()),
                ('next_payout', models.DateTimeField(default=datetime.datetime(2024, 10, 27, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('paypal_email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('percentage_share', models.PositiveIntegerField(default=0)),
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('creator_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creatorfund.creatorfund')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorGroup',
            fields=[
                ('percentage_share', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(blank=True, to='creatorfund.creator')),
            ],
        ),
    ]
