# Generated by Django 5.1.1 on 2024-10-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatorfund', '0001_initial'),
        ('profiles', '0025_profile_passed_milestones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Creator',
        ),
    ]
