# Generated by Django 5.1.1 on 2024-10-10 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorfund', '0002_rename_profile_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='paypal_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
