# Generated by Django 5.1.1 on 2024-10-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorfund', '0005_creatorfund_members_alter_creatorfund_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
