# Generated by Django 5.1.1 on 2024-10-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorfund', '0006_alter_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorfund',
            name='members',
        ),
        migrations.AddField(
            model_name='creatorfund',
            name='members',
            field=models.ManyToManyField(to='creatorfund.creator'),
        ),
    ]
