# Generated by Django 5.1.1 on 2024-10-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorfund', '0009_alter_creatorfund_id_alter_creatorfund_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorfund',
            name='members',
            field=models.ManyToManyField(blank=True, to='creatorfund.creator'),
        ),
    ]
