# Generated by Django 5.1.1 on 2024-10-12 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorfund', '0010_alter_creatorfund_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorfund',
            name='group_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_creator', to='creatorfund.creator'),
            preserve_default=False,
        ),
    ]
