# Generated by Django 5.1.1 on 2024-10-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorfund', '0011_creatorfund_group_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorfund',
            name='group_creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_creator', to='creatorfund.creator'),
        ),
    ]
