# Generated by Django 5.1.1 on 2024-10-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatorfund', '0012_alter_creatorfund_group_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorfund',
            name='group_creator',
        ),
    ]
