# Generated by Django 5.1.1 on 2024-10-12 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorfund', '0013_remove_creatorfund_group_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='paypal_email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
