# Generated by Django 5.1.1 on 2024-10-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorfund', '0014_alter_creator_paypal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='percentage_share',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
