# Generated by Django 5.1.1 on 2024-10-12 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorfund', '0015_alter_creator_percentage_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatorfund',
            old_name='percentage_share',
            new_name='available_money',
        ),
        migrations.RemoveField(
            model_name='creatorfund',
            name='members',
        ),
        migrations.RemoveField(
            model_name='creatorfund',
            name='name',
        ),
        migrations.AddField(
            model_name='creatorfund',
            name='next_payout',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 0, 0)),
        ),
        migrations.AlterField(
            model_name='creatorfund',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CreatorGroup',
            fields=[
                ('percentage_share', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(blank=True, to='creatorfund.creator')),
            ],
        ),
    ]
